steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - compute
      - ssh
      - --project=lab1-404213
      - --zone=us-central1-c
      - my-first-vm
      - --command=cd myProject/StoredProcedures && git pull origin main && mvn clean install




