steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['echo', 'Building...']
  id: BUILD
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['echo', 'Testing...']
  id: TEST  
  - name: gcr.io/cloud-builders/gcloud
    args:
      - compute
      - ssh
      - --project=lab1-404213
      - --zone=us-central1-c
      - my-first-vm
      - --command=cd myProject/StoredProcedures && git pull origin main && mvn clean install


options:
  env:
    - "GCE_ACCOUNT_FILE=/workspace/gce-account.json"
  default_logs_bucket_behavior: "REGIONAL_USER_OWNED_BUCKET"



